### ISSUE TITLE
Add authors

### ISSUE THREAD

**Issue by meevans1** [hsf-training/hsf-training-matplotlib#1]

**Comment by meevans1** [comment]
@allcontributors please add @meevans1 for content

**Comment by klieret** [comment]
@meevans1 In order for the authors to show up on the webpage, set `show_authors: true` in `_config.yml`. I added the small switch to avoid having an empty authors section show up everywhere where we didn't add anyone yet :)

**Comment by klieret** [comment]
This seems to be resolved
