### ISSUE TITLE
Remove the linestyles and markers table and replace it with link to matplotlib docs 

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#128]
Table is rather too long and has empty white spaces on the right-half, maybe copy-paste the content to make it more uniform (~ equal number of rows)

**Comment by klieret** [comment]
I'd be more radical than that and say: Remove the table and instead link to the matplotlib documentation and make it an exercise for students to find how to do a certain marker.

Copying things over is seldom good practice! Better to teach people where to find it!

**Comment by amanmdesai** [comment]
that would be good as well.

**Comment by amanmdesai** [comment]
maybe deleting something would be a good first issue (just for practice)
