### ISSUE TITLE
update sentence 

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#131]
* "Is very important" > "It is very important" for example. 
* "represent in you histogram" > "represent in your histogram"

**Comment by ghost** [comment]
1st merge included in the first sentence, but didn't update the " represent in you histogram". Will do another PR to have both fixed.

**Comment by amanmdesai** [comment]
> 1st merge included in the first sentence, but didn't update the " represent in you histogram". Will do another PR to have both fixed.

No worries. I opened a PR for that. Thanks.

**Comment by ghost** [comment]
Understood, thanks for response.

**Comment by amanmdesai** [comment]
just a minor comment in the latest #135. i think it looks good to me otherwise.  thanks

**Comment by amanmdesai** [comment]
Closed with #135
