### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [hsf-training/hsf-training-matplotlib#137]
Hello @klieret, can you or Alexander Moreno Briceño kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by klieret** [comment]
Something like this: https://github.com/hsf-training/hsf-training-matplotlib/releases/tag/pyhep22  ?

Or should we also add a zenodo ourselves?

**Comment by eduardo-rodrigues** [comment]
The DOI would have been minted if you had set up a "hook" for Zenodo. No worries, I will create the DOI by hand as I've done in several other cases. This will you will see your entry in the Zenodo link I mention above. Thanks.
