### ISSUE TITLE
Refine module and fix minor issues

### ISSUE THREAD

**Issue by amangoel185** [hsf-training/hsf-training-matplotlib#25]
Some minor issues I noticed which we need to fix:

- [x] Recalibrate the timing mentioned in module
- [x] Match all the names for the data and the modules
- [x] Restructure the data repository
- [x] Decide structure for Collab and .ipynb linking
- [x] `FIXME: home page introduction` left out in the [homepage](https://hsf-training.github.io/hsf-training-matplotlib/)
- [x] The link for `HSF training home` in [CONTRIBUTING.md](https://github.com/hsf-training/hsf-training-matplotlib/blob/gh-pages/CONTRIBUTING.md) is broken (this extends to a lot of other hsf-training repositories too).
- [x] Wrong formatting for `issues` URL in [README.md](https://github.com/hsf-training/hsf-training-matplotlib/blob/gh-pages/README.md)
- [x] Reduce image size all over the module (reopened in #60)
- [x] Add information to the [CITATION](https://github.com/hsf-training/hsf-training-matplotlib/blob/gh-pages/CITATION) file (reopened in #61)
- [x] Also adding the dump for `make lesson-check`: (obsolete now, needs to be checked after updating the module)
```
index.md:8:FIXME: home page introduction
reference.md:7:FIXME
_extras/discuss.md:4:FIXME
_extras/guide.md:4:FIXME
./_episodes/02-physics.md:20: Unknown or missing blockquote type None
./_episodes/05-dimuonspectrum.md:192: Unknown or missing blockquote type None
Problems detected but ignored (permissive mode).
```

**Comment by klieret** [comment]
Can you open separate issues for what's left so we can parallelize more easily at the hackathon? @amangoel185

**Comment by amangoel185** [comment]
I have opened two new issues (#60 and #61) for the pending tasks. Closing this issue now.
