### ISSUE TITLE
Fix the "Key Points" for each chapter

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-matplotlib#26]
In each section, the "Key points" at the bottom are quite empty. Such sections are a great opportunity to highlight what students should have learned and confirm if the goals were reached, or something else must be reviewed again. 

Please check the Key Points for the chapters.

**Comment by klieret** [comment]
Hi @michmx . Can this be closed?

**Comment by michmx** [comment]
Sorry for the very late comment, @klieret. I will take a look at the chapters and include key points.
