### ISSUE TITLE
Add example to the "Linestyles and markers" section.

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#63]

**Comment by amanmdesai** [comment]
plt.plot(x1,y1,'--k',label="Black Dashed line")
plt.plot(x1,y2,':g',label="Green Dotted line style")
plt.plot(x1,y3,'o b',label="Blue Circle marker")
plt.legend()
plt.show()

maybe add these lines to the section ?

**Comment by klieret** [comment]
Sounds good :)

I'd say we should include this as an exercise even

But please use the `fig, ax = ...; ax.plot(..)` style (see the updated previous examples)

**Comment by amanmdesai** [comment]
Yes sure we can include this as an exercise. Here is the updated code: 

fig, ax = plt.subplots()  # Create a figure containing a single axes.
ax.plot(x1,y1,linestyle='--',label="Dashed line")
ax.plot(x1,y2,linestyle=':',label="Dotted line style")
ax.plot(x1,y3,marker='o',label="Circle marker")
ax.legend()
plt.show()

**Comment by klieret** [comment]
Could you run [black](https://github.com/psf/black) on this snippet?

Then you could wrap it in an exercise block and open a PR for it :)
