### ISSUE TITLE
Use f-strings (episode 4)

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-matplotlib#76]
```
for s in samples:
    print(s,"      After selection: ", len(branches[s]["m4l"][selection_events[s]]))
```

should use f-strings

**Comment by klieret** [comment]
Also a lot of `varname + units` should better be f-strings

**Comment by GuillermoFidalgo** [comment]
Is there a preference to using f strings over the text formatting method?
I don't know f-strings myself in detail, are they interchangeable? Is there a benefit of one over the other?
```python
text = " number of words is {} random text"
print(text.format(10))
```

**Comment by klieret** [comment]
I think so.

* f-strings are usually more readable (no more jumping back and forth with placeholders)
* they are faster see e.g., [SO](https://stackoverflow.com/a/43123579/)

The example shown on top is a third option, but I don't think it's recommended (also slightly slower than f-strings). 
Also python advocates the "only one way to do things" approach. And since f-strings support a superset of options of the multiple-arguments approach, they should be prepared.

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?

**Comment by amangoel185** [comment]
Hi @Vaibhav-Chopra-GT, feel free to work on it! We're happy to have you here. :) Let us know if you need any help!
