### ISSUE TITLE
OO API + black formatting for episode 5

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#88]
Following issue #83 for episode 5 mplhep

**Comment by klieret** [comment]
To me it looks like episode 5 is already converted though, right? Or did I miss something?

**Comment by amanmdesai** [comment]
when I ran black command, I see the following output: 

1 file reformatted for some of the snippets

This is only for 4 of the snippets or so

**Comment by amanmdesai** [comment]
> To me it looks like episode 5 is already converted though, right? Or did I miss something?

Yes, you are right. Episode 5 is already converted. 

Any other episode that needs to be converted?

**Comment by klieret** [comment]
> when I ran black command, I see the following output:
> 
> 1 file reformatted for some of the snippets
> 
> This is only for 4 of the snippets or so

Oh, if there's more, feel free to open PRs for it.

I'm not aware of any other snippets other than those of episode 1 (#83)

**Comment by amanmdesai** [comment]
Hi, I tried to run black on some snippets and the comparison can be seen here:

https://github.com/hsf-training/hsf-training-matplotlib/compare/gh-pages...amanmdesai:hsf-training-matplotlib:test-episode-5-black?diff=split


Could you please take a look and see if this is what we want? (I am a bit confused here). 

Thanks.

**Comment by klieret** [comment]
Oh, indeed!! 

I had only taken a quick look and thought it had already been applied.

Yes, please open a PR for it!
