### ISSUE TITLE
Overall structure and plan of action for the module

### ISSUE THREAD

**Issue by amangoel185** [hsf-training/hsf-training-matplotlib#9]
These are the key points that @meevans1 and I discussed for the module. We need to keep in mind and add/do the following things going forward:

- [x] Notebook Links on the webpage need to be corrected
- [x] ~~Fix the GIF rendering in the main notebooks~~ (not required)
- [x] Add a _Physics Background_ page that discusses the relevant concepts used in the plots - @meevans1 
- [x] Add a _Data Discussion_ page that discusses the dataset being worked on - @meevans1 
- [x] Order of all the functions (which needs to be done first and how to build upon it) - @meevans1 
- [x] Code needs to be broken down into challenges as mentioned in #5 and #6
- [x] Information between the notebooks and the webpage needs to be unified 
- [x] Checkpoints showing expected plots for the students
- [x] Picture of the final solution

**Comment by meevans1** [comment]
*Physics background* and *Data Discussion* tasks done in commit 797d1b8746107e00a7ad44910842873983cb38ed

**Comment by meevans1** [comment]
*Order of all the functions* done in commit 26705a974e6a85b1f9d3ad70cee882dec469f10f

**Comment by meevans1** [comment]
Hi @amangoel185 I've done the tasks you tasked you've tagged me in. Are you ok to start on the rest? Let me know if you need me for any part.

**Comment by meevans1** [comment]
*Notebook link* fixed in 1b8777e26fd5800470913fd6463bea67b553244e

**Comment by meevans1** [comment]
Issues #5 , #6, #7 have been reviewed and closed
