### ISSUE TITLE
Add Feynman diagrams for Background Processes (such as ZZ, others)

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-matplotlib#97]
Feynman diagrams for the main signal process are already given, however there is no Feynman diagram for the background processes. 

It will be useful to have some Feynman diagrams for the background processes.

**Comment by amanmdesai** [comment]
@klieret   what is your opinion about this?

**Comment by klieret** [comment]
So how many diagrams would that be? And would they directly tie in to some of the things that are explained in the tutorial later on (as in, will you actually refer back to them in one of the episodes)? 

My personal opinion is that the the course shouldn't focus too much on the physics (because people of different levels of physics understanding are completely mixed, so it'll only be at the right level for a small fraction...)

**Comment by amanmdesai** [comment]
Thanks @klieret.

Two (example) diagrams for the MC samples used in the lecture should suffice. 
 
1. llll (without higgs)
2. Zee & Zmumu

+ a few (2-3) sentences on what we mean by "background". The idea is illustrate what we mean by background explicitly in the episode (I could not find that in the module). 

Perhaps for someone it could be confusing as to why we are using ZZ, Zee, and Zmumu samples when talking about Higgs to 4lepton. One could show that explicitly by including the above. The [episode-3](https://hsf-training.github.io/hsf-training-matplotlib/03-physics/index.html) would be the place to add it, I guess. Thats the plan I had.

This would be helpful to refer to the diagrams when discussing about samples [here](https://hsf-training.github.io/hsf-training-matplotlib/04-higgs-search/index.html#:~:text=it%20explicitly%20there.-,Samples,-In%20the%20following).

**Comment by klieret** [comment]
Yes, I guess adding two diagrams and a few sentences wouldn't hurt :) 

(I'm still going to mark this as low priority, because it doesn't have anything to do with mpl)

**Comment by amanmdesai** [comment]
Thanks @klieret!

**Comment by klieret** [comment]
Also note the discussion in #99
